# Using Pandas and NumPy
## Portfolio and Risk
- Pandas Datareader
- Pandas
- Numpy
- Portfolio and return

### Resources
- Pandas Datareader
https://pandas-datareader.readthedocs.io/ (https://youtu.be/sgndYho8RyI)
- Pandas https://pandas.pydata.org (https://youtu.be/m8ahf_c9hEc)
- NumPy http://numpy.org (Focus here)

### Pandas Datareader & Pandas DataFrame

In [1]:
import numpy as np
import pandas_datareader as pdr
import datetime as dt
import pandas as pd
from datetime import datetime

In [2]:
!pip install pandas_datareader

In [3]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas_datareader.data as pdr
import yfinance as yfin
yfin.pdr_override()

In [5]:
start = dt.datetime(2020, 1, 1)
data = pdr.get_data_yahoo("AAPL", start)

[*********************100%***********************]  1 of 1 completed


In [6]:
data.head()

Open       High        Low      Close  Adj Close     Volume
Date                                                                        
2020-01-02  74.059998  75.150002  73.797501  75.087502  73.449394  135480400
2020-01-03  74.287498  75.144997  74.125000  74.357498  72.735336  146322800
2020-01-06  73.447502  74.989998  73.187500  74.949997  73.314888  118387200
2020-01-07  74.959999  75.224998  74.370003  74.597504  72.970078  108872000
2020-01-08  74.290001  76.110001  74.290001  75.797501  74.143898  132079200

In [7]:
data.index

DatetimeIndex(['2020-01-02', '2020-01-03', '2020-01-06', '2020-01-07',
               '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-13',
               '2020-01-14', '2020-01-15',
               ...
               '2023-03-17', '2023-03-20', '2023-03-21', '2023-03-22',
               '2023-03-23', '2023-03-24', '2023-03-27', '2023-03-28',
               '2023-03-29', '2023-03-30'],
              dtype='datetime64[ns]', name='Date', length=817, freq=None)

In [8]:
data.dtypes

Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [9]:
type(data)

pandas.core.frame.DataFrame

### NumPy

In [10]:
data.to_numpy()

array([[7.40599976e+01, 7.51500015e+01, 7.37975006e+01, 7.50875015e+01,
        7.34493942e+01, 1.35480400e+08],
       [7.42874985e+01, 7.51449966e+01, 7.41250000e+01, 7.43574982e+01,
        7.27353363e+01, 1.46322800e+08],
       [7.34475021e+01, 7.49899979e+01, 7.31875000e+01, 7.49499969e+01,
        7.33148880e+01, 1.18387200e+08],
       ...,
       [1.57970001e+02, 1.58490005e+02, 1.55979996e+02, 1.57649994e+02,
        1.57649994e+02, 4.59922000e+07],
       [1.59369995e+02, 1.61050003e+02, 1.59350006e+02, 1.60770004e+02,
        1.60770004e+02, 5.13057000e+07],
       [1.61529999e+02, 1.62470001e+02, 1.61270004e+02, 1.62360001e+02,
        1.62360001e+02, 4.94567000e+07]])

In [11]:
arr = data.to_numpy()

In [12]:
arr.shape

(817, 6)

In [13]:
len(data)

817

In [14]:
arr[0]

array([7.40599976e+01, 7.51500015e+01, 7.37975006e+01, 7.50875015e+01,
       7.34493942e+01, 1.35480400e+08])

In [15]:
data.head(1)

Open       High        Low      Close  Adj Close     Volume
Date                                                                        
2020-01-02  74.059998  75.150002  73.797501  75.087502  73.449394  135480400

In [16]:
arr.dtype

dtype('float64')

In [17]:
small = arr[:10, 0].copy()

In [18]:
small

array([74.05999756, 74.28749847, 73.44750214, 74.95999908, 74.29000092,
       76.80999756, 77.65000153, 77.91000366, 79.17500305, 77.96250153])

In [19]:
data.head()

Open       High        Low      Close  Adj Close     Volume
Date                                                                        
2020-01-02  74.059998  75.150002  73.797501  75.087502  73.449394  135480400
2020-01-03  74.287498  75.144997  74.125000  74.357498  72.735336  146322800
2020-01-06  73.447502  74.989998  73.187500  74.949997  73.314888  118387200
2020-01-07  74.959999  75.224998  74.370003  74.597504  72.970078  108872000
2020-01-08  74.290001  76.110001  74.290001  75.797501  74.143898  132079200

In [20]:
np.max(small)

79.17500305175781

In [21]:
small.max()

79.17500305175781

In [22]:
small.argmax()

8

In [23]:
small

array([74.05999756, 74.28749847, 73.44750214, 74.95999908, 74.29000092,
       76.80999756, 77.65000153, 77.91000366, 79.17500305, 77.96250153])

In [24]:
small[small.argmax()]

79.17500305175781

In [25]:
np.log(small)

array([4.30487554, 4.30794268, 4.29657089, 4.31695463, 4.30797637,
       4.34133481, 4.35221157, 4.35555436, 4.37166063, 4.35622796])

In [26]:
np.log(data)

Open      High       Low     Close  Adj Close     Volume
Date                                                                    
2020-01-02  4.304876  4.319486  4.301325  4.318654   4.296597  18.724338
2020-01-03  4.307943  4.319420  4.305753  4.308885   4.286827  18.801326
2020-01-06  4.296571  4.317355  4.293025  4.316821   4.294764  18.589471
2020-01-07  4.316955  4.320484  4.309053  4.312107   4.290049  18.505683
2020-01-08  4.307976  4.332180  4.307976  4.328065   4.306008  18.698912
...              ...       ...       ...       ...        ...        ...
2023-03-24  5.068023  5.077297  5.061645  5.076735   5.076735  17.896373
2023-03-27  5.074799  5.079975  5.061772  5.064366   5.064366  17.774232
2023-03-28  5.062405  5.065692  5.049728  5.060377   5.060377  17.643982
2023-03-29  5.071229  5.081715  5.071103  5.079975   5.079975  17.753312
2023-03-30  5.084691  5.090493  5.083080  5.089816   5.089816  17.716608

[817 rows x 6 columns]

In [27]:
data/data.shift()

Open      High       Low     Close  Adj Close    Volume
Date                                                                   
2020-01-02       NaN       NaN       NaN       NaN        NaN       NaN
2020-01-03  1.003072  0.999933  1.004438  0.990278   0.990278  1.080029
2020-01-06  0.988693  0.997937  0.987352  1.007968   1.007968  0.809082
2020-01-07  1.020593  1.003134  1.016157  0.995297   0.995297  0.919626
2020-01-08  0.991062  1.011765  0.998924  1.016086   1.016086  1.213160
...              ...       ...       ...       ...        ...       ...
2023-03-24  1.000189  0.992510  1.001078  1.008306   1.008306  0.875402
2023-03-27  1.006798  1.002682  1.000127  0.987707   0.987707  0.885024
2023-03-28  0.987683  0.985818  0.988028  0.996020   0.996020  0.877876
2023-03-29  1.008862  1.016152  1.021605  1.019791   1.019791  1.115530
2023-03-30  1.013553  1.008817  1.012049  1.009890   1.009890  0.963961

[817 rows x 6 columns]

In [28]:
data.head()

Open       High        Low      Close  Adj Close     Volume
Date                                                                        
2020-01-02  74.059998  75.150002  73.797501  75.087502  73.449394  135480400
2020-01-03  74.287498  75.144997  74.125000  74.357498  72.735336  146322800
2020-01-06  73.447502  74.989998  73.187500  74.949997  73.314888  118387200
2020-01-07  74.959999  75.224998  74.370003  74.597504  72.970078  108872000
2020-01-08  74.290001  76.110001  74.290001  75.797501  74.143898  132079200

In [29]:
75.144997/75.150002

0.9999333998687053

In [30]:
np.sum(np.log(data/data.shift()))

Open         0.779815
High         0.771007
Low          0.781755
Close        0.771162
Adj Close    0.793219
Volume      -1.007729
dtype: float64

In [31]:
np.log(data/data.iloc[0]).tail(1)

Open      High       Low     Close  Adj Close    Volume
Date                                                                   
2023-03-30  0.779815  0.771007  0.781755  0.771162   0.793219 -1.007729

In [32]:
small.shape

(10,)

In [33]:
small

array([74.05999756, 74.28749847, 73.44750214, 74.95999908, 74.29000092,
       76.80999756, 77.65000153, 77.91000366, 79.17500305, 77.96250153])

In [34]:
small.reshape(2, 5)

array([[74.05999756, 74.28749847, 73.44750214, 74.95999908, 74.29000092],
       [76.80999756, 77.65000153, 77.91000366, 79.17500305, 77.96250153]])

In [35]:
small.reshape(10, 1)

array([[74.05999756],
       [74.28749847],
       [73.44750214],
       [74.95999908],
       [74.29000092],
       [76.80999756],
       [77.65000153],
       [77.91000366],
       [79.17500305],
       [77.96250153]])

In [36]:
small.reshape(-1, 1)

array([[74.05999756],
       [74.28749847],
       [73.44750214],
       [74.95999908],
       [74.29000092],
       [76.80999756],
       [77.65000153],
       [77.91000366],
       [79.17500305],
       [77.96250153]])

### Portfolios

In [37]:
tickers = ['AAPL', 'MSFT', 'TWTR', 'IBM']
start = dt.datetime(2020, 1, 1)

data = pdr.get_data_yahoo(tickers, start)

[*********************100%***********************]  4 of 4 completed

1 Failed download:
- TWTR: No timezone found, symbol may be delisted


In [38]:
data.head()

Adj Close                                   Close  \
                          AAPL         IBM        MSFT TWTR       AAPL   
Date                                                                     
2020-01-02 00:00:00  73.449387  110.232506  155.761780  NaN  75.087502   
2020-01-03 00:00:00  72.735313  109.353386  153.822296  NaN  74.357498   
2020-01-06 00:00:00  73.314888  109.158020  154.219940  NaN  74.949997   
2020-01-07 00:00:00  72.970093  109.231262  152.813751  NaN  74.597504   
2020-01-08 00:00:00  74.143898  110.142975  155.247833  NaN  75.797501   

                                                       High              ...  \
                            IBM        MSFT TWTR       AAPL         IBM  ...   
Date                                                                     ...   
2020-01-02 00:00:00  129.464630  160.619995  NaN  75.150002  129.942642  ...   
2020-01-03 00:00:00  128.432129  158.619995  NaN  75.144997  128.929260  ...   
2020-01-06 00:00:00  128.202682  159.029999  NaN  74.989998  128.336517  ...   
2020-01-07 00:00:00  128.288712  157.580002  NaN  75.224998  129.024857  ...   
2020-01-08 00:00:00  129.359467  160.089996  NaN  76.110001  129.885284  ...   

                            Low            Open                               \
                           MSFT TWTR       AAPL         IBM        MSFT TWTR   
Date                                                                           
2020-01-02 00:00:00  158.330002  NaN  74.059998  129.063095  158.779999  NaN   
2020-01-03 00:00:00  158.059998  NaN  74.287498  127.695984  158.320007  NaN   
2020-01-06 00:00:00  156.509995  NaN  73.447502  127.552582  157.080002  NaN   
2020-01-07 00:00:00  157.320007  NaN  74.959999  127.810707  159.320007  NaN   
2020-01-08 00:00:00  157.949997  NaN  74.290001  128.594650  158.929993  NaN   

                        Volume                          
                          AAPL      IBM      MSFT TWTR  
Date                                                    
2020-01-02 00:00:00  135480400  3293436  22622100  NaN  
2020-01-03 00:00:00  146322800  2482890  21116200  NaN  
2020-01-06 00:00:00  118387200  2537073  20813700  NaN  
2020-01-07 00:00:00  108872000  3232977  21634100  NaN  
2020-01-08 00:00:00  132079200  4545916  27746500  NaN  

[5 rows x 24 columns]

In [39]:
data = data['Adj Close']

In [40]:
data.head()

AAPL         IBM        MSFT  TWTR
Date                                                        
2020-01-02 00:00:00  73.449387  110.232506  155.761780   NaN
2020-01-03 00:00:00  72.735313  109.353386  153.822296   NaN
2020-01-06 00:00:00  73.314888  109.158020  154.219940   NaN
2020-01-07 00:00:00  72.970093  109.231262  152.813751   NaN
2020-01-08 00:00:00  74.143898  110.142975  155.247833   NaN

In [41]:
portfolios = [.25, .15, .40, .20]

In [42]:
np.sum(portfolios)

1.0

In [43]:
(data/data.iloc[0])*portfolios*100000

AAPL           IBM          MSFT  TWTR
Date                                                      
2020-01-02  25000.000000  15000.000000  40000.000000   NaN
2020-01-03  24756.950597  14880.372872  39501.935932   NaN
2020-01-06  24954.220654  14853.788258  39604.051879   NaN
2020-01-07  24836.862551  14863.754763  39242.939168   NaN
2020-01-08  25236.391155  14987.816986  39868.017293   NaN
...                  ...           ...           ...   ...
2023-03-24  54544.362937  17048.963916  72051.053272   NaN
2023-03-27  53873.832755  17595.989035  70975.050558   NaN
2023-03-28  53659.397716  17600.071150  70679.729357   NaN
2023-03-29  54721.357019  17650.420687  72035.645754   NaN
2023-03-30  55262.544772  17583.742693  72944.720633   NaN

[817 rows x 4 columns]

In [44]:
weight = np.random.random(4)
weight /= weight.sum()
weight

array([0.41633123, 0.13015255, 0.21382379, 0.23969242])

In [45]:
weight.sum()

1.0

In [46]:
np.sum((data/data.iloc[0])*portfolios*100000, axis=1)

Date
2020-01-02     80000.000000
2020-01-03     79139.259401
2020-01-06     79412.060791
2020-01-07     78943.556482
2020-01-08     80092.225434
                  ...      
2023-03-24    143644.380124
2023-03-27    142444.872349
2023-03-28    141939.198224
2023-03-29    144407.423460
2023-03-30    145791.008097
Length: 817, dtype: float64

In [47]:
np.sum((data/data.iloc[0])*weight*100000, axis=1)

Date
2020-01-02     76030.757728
2020-01-03     75255.958122
2020-01-06     75615.996873
2020-01-07     75236.169049
2020-01-08     76343.302197
                  ...      
2023-03-24    144142.768489
2023-03-27    142925.575195
2023-03-28    142414.146418
2023-03-29    144951.159145
2023-03-30    146280.511783
Length: 817, dtype: float64